### ISSUE TITLE
Songs stop playing halfway through

### ISSUE THREAD

**Issue by IronMaltese** [snuffyDev/Beatbump#20]
Songs just stop playing halfway through, but the bar keeps moving like they’re still playing

**Comment by snuffyDev** [comment]
On iOS? Or on a different device?

**Comment by IronMaltese** [comment]
> On iOS? Or on a different device?
I’m on iOS 15.2.1 and when I have songs play in the background, a lot of the time the song stops but the progress bar keeps moving like the song is still playing

**Comment by snuffyDev** [comment]
Can you verify for me that your Safari settings replicates the changes described [on this wiki page](https://github.com/snuffyDev/Beatbump/wiki/Fixing-Background-Autoplay-on-iOS-15)?

**Comment by IronMaltese** [comment]
![Uploading 44E0723F-40DC-4E53-B86C-CBF53FF6EC02.png…]()

**Comment by IronMaltese** [comment]
![A06E423D-0D10-4819-8111-1C54E24C0356](https://user-images.githubusercontent.com/89056889/150719707-220628a2-27e5-46b7-afb3-068c326b9e76.png)

**Comment by IronMaltese** [comment]
Lmk if I would have to change any other settings, or if it’s a problem with the code, Thanks

**Comment by snuffyDev** [comment]
Your settings seem to be perfectly fine, which makes it even more of a mystery considering on Windows, Android, as well as my iPhone this issue hasn't appeared even after 30 mins of continuous playback for each device. I will use LambdaTest in addition to see if I get lucky and encounter the bug.

In hopes of finding anything awry in the code, albeit the majority of potentially related code hasn't changed drastically, I'm gonna be looking at potential problem areas. The description you gave of the bug almost matches what happens when the iOS check fails, but after the song plays fully, theres just silence, doubling the length of the track.

Does the Player recover on its own and loads the next track at any point? Do either of the skip buttons next to the play button change the track? Or does it just fail to do anything, with or without input? 

Furthermore, how often does this happen? Does it happen only on certain pages, like playlists, or trending, etc.? Does it seemingly just happen at random, or only on certain tracks?

Appreciate the issue being created, and also appreciate any further detail you can provide to any of my questions! Many thanks

**Comment by IronMaltese** [comment]
I haven’t been able to replicate this issue all day, but that doesn’t mean it doesn’t happen often, I’ll update you with more info if it happens again

**Comment by snuffyDev** [comment]
Appreciate the update, as well as any future updates. Haven't been able to figure out any potential causes yet

**Comment by IronMaltese** [comment]
This problem has happened twice in the last three days, and the skip next song buttons still work, but the song has to silently finish before the next song plays

**Comment by snuffyDev** [comment]
Doing some thinking had me realize that there was only one time something similar happened. Except my issue wasn’t the songs duration being doubled, but that in the Notification Center a song had the correct length. When the song ended it ended as it should’ve, but when I went back the song had the bugged duration.

Now the question is, is it a Google issue involving their headers they send or if it’s WebKit being picky.

**Comment by IronMaltese** [comment]
This problem is very rare, and it hasn’t happened since I replied to this issue, so I honestly don’t think this should be worried about unless other users prove to have the same problem

**Comment by snuffyDev** [comment]
Okay thats good to hear, my understanding originally was that it was a frequent occurrence. I’ll leave this open in case anyone else comes across it

**Comment by IronMaltese** [comment]
This problem has been happening very frequently recently, and it only happens when I close out safari, the song keeps playing, and autoplay stills works but sometimes the song just stops the audio but the bar keeps moving, then the next song plays when it's supposed to be done, maybe this is an issue with the API used to fetch YouTube audio, or something to do with the settings, but I just wanted to update you that this seems to be a more common occurrence for me than otherwise thought before and that it only really happens when the screen is off or safari is closed
