### ISSUE TITLE
Use album image when playing songs

### ISSUE THREAD

**Issue by IronMaltese** [snuffyDev/Beatbump#23]
Instead of showing the YouTube video’s image when playing a song, the song’s album cover should be shown

**Comment by snuffyDev** [comment]
I've thought about that early on. Unfortunately, the only options for how it can be implemented are

> Send a search to YTM, parse the data, find the album thumbnail, send it back
or
> Send a HTTP request to a 3rd party API/DB and get the thumbnail that way.

Problem with the first option is how much processing would need to be done (which is a lot). The second one is a better option, but that would mean being dependent on the chosen 3rd party service - which wouldn't be optimal. Not to mention, either method would mean songs would load slower, since there'd be an added HTTP request for each song load.

If you have any suggestions or any better solutions let me know, I'll see what I can do

**Comment by IronMaltese** [comment]
Yeah that’s about what I expected, but it was worth a shot

**Comment by IronMaltese** [comment]
You can prolly close this issue, but it’s up to you

**Comment by IronMaltese** [comment]
https://user-images.githubusercontent.com/89056889/157370137-a5261f9c-d397-41fa-9958-bbc852856d8c.MOVThis song has a music video, but when searching for it, the album art is shown, but when playing it in the album the music video thumbnail is shown, could the same source be parsed for each that would allow the song to always show the album art?

**Comment by IronMaltese** [comment]
https://user-images.githubusercontent.com/89056889/157370326-af463482-85a6-401a-8d61-a4989d01eb62.MOV

**Comment by snuffyDev** [comment]
> [user-images.githubusercontent.com/89056889/157370137-a5261f9c-d397-41fa-9958-bbc852856d8c.MOV](https://user-images.githubusercontent.com/89056889/157370137-a5261f9c-d397-41fa-9958-bbc852856d8c.MOV) This song has a music video, but when searching for it, the album art is shown, but when playing it in the album the music video thumbnail is shown, could the same source be parsed for each that would allow the song to always show the album art?

Unfortunately, I don't think I'll be able to do much about that. The reason the album art shows when you search it is because 'Songs' is the default search filter, which will only show audio-only official song releases (their thumbnails are the album art).
If a song has a music video, then they're two totally different uploads, which have different IDs so therefore the API returns different data for them. 

|<img src="https://user-images.githubusercontent.com/72365477/157375808-cefed4b4-5ee4-4bc1-8d65-d65e0e99a5cb.jpeg"/>| <img src="https://user-images.githubusercontent.com/72365477/157376143-541b3238-6241-4bf3-97e8-fbe35f508bec.jpeg"/>| 
|--|-- |
|<p align="center">Song ID is: <code>9BrQUWQV1XQ</code></p> | <p align="center">Video ID is: <code>aNYjOVo5IEw</code></p> |

YouTube Music also has this annoyingly, since when the album was uploaded to their site, for whatever reason the video was chosen to be in the album instead of the song (https://music.youtube.com/watch?v=9BrQUWQV1XQ)

<img src="https://user-images.githubusercontent.com/72365477/157375520-5ea1218e-4a77-45f9-b0db-a0c1fabf1b0b.jpeg" width="75%"/>

**Comment by IronMaltese** [comment]
Dang, that sucks :/
