### ISSUE TITLE
Unable to search tracks

### ISSUE THREAD

**Issue by onny** [snuffyDev/Beatbump#8]
Hey,
unfortunately it is currently not possible to search for tracks.
For example: https://beatbump.ml/search/%2520Copla%2520Guajira%2520-%2520Ibrahim%2520Ferrer?filter=EgWKAQIIAWoKEAMQBBAKEAkQBQ%3D%3D

Best regards
Jonas

**Comment by snuffyDev** [comment]
Hello, my apologies for the late response! Was the issue related to scrolling, possibly? If so, it should be fixed now. Before I fell asleep I must've messed with some CSS, without realizing the outcome until I woke up. 

If the issue isn't scrolling related, then do you have any description of what happens when you search? I've tried that link and it appears to be working fine. Please let me know whenever you see this! Thanks!

**Comment by onny** [comment]
Works for me too now. Maybe it was a connectivity issue? Thank you for your feedback :)

Regards
Jonas
