### ISSUE TITLE
Site stopped working

### ISSUE THREAD

**Issue by yuval-herman** [snuffyDev/Beatbump#80]
Site doesn't work properly to me right now.
Front page does seam to show songs as per usual however none seam to play.
Search doesn't seam to work for any song at all.
Could be related to #79?

**Comment by IronMaltese** [comment]
Same for me, but the rewrite page works for me, this shouldn't be a problem since the rewrite is getting released soon

**Comment by snuffyDev** [comment]
Odd. It works for me, but soon I should have the loose ends of the rewrite all tied up! Just working on a few minor/major UI issues primarily!

Haven’t uploaded any of the new code to the main site, but we will see soon (hopefully today) if the new code is the fix to this!

![DE63877F-CBF6-4C13-AA74-AD6BC5F50084](https://user-images.githubusercontent.com/72365477/179352153-a75f0104-b5a6-4abd-b20e-820a61a6d031.png)

![E8A0BEEA-C1D5-4820-B7EF-B593DBFC899F](https://user-images.githubusercontent.com/72365477/179352151-dbfb01f9-0802-4c22-8277-78e349e99ba9.png)

**Comment by snuffyDev** [comment]
Or was this related to the rewrite preview? My apologies! I realized this after I woke up since I upgraded SvelteKit before bed, didn’t realize they changed the endpoint methods to be capitalized! Rewrite preview site should be working now! Thanks for the issue! 

Let me know if you encounter any further problems

**Comment by yuval-herman** [comment]
Works now, thanks!
