### ISSUE TITLE
Long custom playlists (> 10000 songs) make the website unusably slow.

### ISSUE THREAD

**Issue by noughtmare** [snuffyDev/Beatbump#96]
I would like to mix all the songs of a few similar artists. The combined number of songs is over 10000.

First of all, loading the playlist page is very slow. Maybe some sort of pagination could be used? Even cutting it into pages of 1000 songs would probably already help a lot and not bother most people with reasonably sized playlists.

Secondly, playing songs from the playlist is possible but it causes the whole UI to stop working. After starting the playlist I can only use the previous and next song buttons. The rest of the buttons all seem to do nothing.

**Comment by snuffyDev** [comment]
Is this a publicly accessible (ie. actually on YouTube Music) playlist, or a custom playlist?

The UI breaking sounds like it could be a custom playlist problem.

If it's a public playlist, what is the URL? I'll use it as a point of reference while slugging through the optimization process (it's been planned for awhile, but should really get done ASAP honestly).

Perhaps using a virtual list (like the Search page uses) would be the solution for most of the performance related problems?

---

(just "thinking out loud" so my idea of what's happening is jotted down) -- 

Recently when making a text/code-editor for the browser I ran into problem similar to this when typing into the editor with a 90k+ text source, since each keystroke would update all 90k characters in the DOM. 

It's safe to assume that's what's causing the performance problems,

![image](https://user-images.githubusercontent.com/72365477/187415135-e798a2cf-8335-405f-b045-311962d25d11.png)

Here's the playlist I am testing with (i believe it's ~4.5k songs ? ) https://beatbump.ml/playlist/VLPL77A9600E406FD23A

**Comment by noughtmare** [comment]
It's a custom playlist. The URL for me is https://beatbump.ml/library/playlists/7QuZEzNTcQDXc-taAE0QogUCTKyeIVY1, but I don't know if that is useful because opening that on other devices doesn't work for me.

It is also a bit strange that scrolling the page and hovering over songs in the playlist does also still work. And Firefox isn't showing me the message about a script taking too long to run. So, I don't know what exactly is causing most of the buttons to stop working.

**Comment by noughtmare** [comment]
Oh and it seems that the youtube playlists do have a on-demand scrolling feature that doesn't load everything at once. So the UI is much faster.

**Comment by noughtmare** [comment]
> The UI breaking sounds like it could be a custom playlist problem.

Yes, now that you say it. It looks like any custom playlist will break the UI in that way. So this issue is really two separate issues: 

1. The playlist view of custom playlists is slow if the playlist is very long
2. Playing songs from a custom playlist breaks the UI

There could be a third problem with the performance of large custom playlists while playing, but I can't really test that before the other issue get fixed.

**Comment by snuffyDev** [comment]
Would you mind if I asked if you'd be able to send me your Beatbump playlists? If you're okay with it, it'd be a big help since it would help me with making sure this problem gets fully solved.

The button to send your playlists over is here: 

![image](https://user-images.githubusercontent.com/72365477/187427903-0f3d0038-4b7f-45f5-902c-0e7605ecc03e.png)

Then you'll see a popup come up, hit Next Step and choose the "Sending" button when it asks if you'll be sending or receiving.

Eventually it'll ask you to enter in the Receiver's (that's me), my ID is `bb-xtj2fk4`. It'll send the data right over to me without having to do anything extra outside of Beatbump

**Comment by snuffyDev** [comment]
I feel like such an idiot, my bad! I was on the dev server. Haven't had my morning cigarette just yet. Hate to be a pain but (hopefully) should work this time around since I'm on the live site, if you're willing to do that one more time for me.

Last time I'll bug you lol, `bb-xe2t1tg`

**Comment by snuffyDev** [comment]
Thank you! I received the data this time, my bad! I'm working on both problems (plus apparent issues with the code I wrote to sync data) right now!

**Comment by noughtmare** [comment]
I still don't seem to be able to share my playlist, but I can give you the exact steps to reproduce my problem:

1. Create a new custom playlist
2. Go to https://beatbump.ml/playlist/VLOLAK5uy_kVl1fznIOKKu8tUtyiVKIDDtMc0GCgNX0
3. Click the three dots and then add to playlist and add it to the playlist you just created.

Now looking at the library view for me something strange already happens. Every time I refresh the page the number of songs in the playlist gets bigger. It starts with less than 1000 songs but grows with around 150 songs repeatedly to almost 10000 and it is still growing for me.

Viewing the actual songs in the playlist shows that the first song is "undefined" with a length of 149.

And trying to start the playlist breaks the UI as I described earlier.

**Comment by snuffyDev** [comment]
![image](https://user-images.githubusercontent.com/72365477/187431152-66298684-d51f-45e8-886a-f7fe148619c8.png)

Okay, good news I hope. The `undefined` "track" is actually a playlist that was merged incorrectly (my fault, not yours!)

![image](https://user-images.githubusercontent.com/72365477/187431402-ad0022a9-01ba-4811-97b6-1eb1454eeb51.png)

This issue should be already "fixed" since I have a 'migration' bit in the `db` module (found here: https://github.com/snuffyDev/Beatbump/blob/master/app/src/lib/db.ts#L318). I'll make sure to test it out locally before pushing an update, so I'd say within the hour this part of the problem should be fixed.


https://user-images.githubusercontent.com/72365477/187433474-370bc20a-eeae-4783-a94a-a176d01a0dd1.mp4

Hopefully that's the only issue, seeing as other local playlists I've made work without breaking the app. 

I'll let you know updates on progress that I've made with this, whenever I have more info to share!

**Comment by snuffyDev** [comment]
Annndddd... Good news! Managed to get it working, along with fixing an issue I accidentially introduced to both the IndexedDB code as well as with handling playback errors!

![image](https://user-images.githubusercontent.com/72365477/187439710-40e4f571-2aa1-4f38-ae1e-f99b0b33e0df.png)
*(all the 'items' in the playlist will automatically fix itself after I push this update soon!)*

https://user-images.githubusercontent.com/72365477/187444059-92ec2236-50a8-4e33-9e47-767969fc0b40.mp4

And to show playback working, here's a video as well!

I will push the update as soon as I can, I'm going to quickly add in Database import/export buttons just so that way it'll be able to be used.

---

As for the performance problems, unfortunately at this very second, they still are going to be present for the next day or two (hopefully it'll be resolved within that time!).

If I move the IndexedDB logic to a Web Worker performance should be improved massively, since it'll do all the heavy lifting in a separate thread. This would be great in terms of UX and overall usability! 

Another performance issue pops up when loading a very large number of tracks into memory, since right now it would have to keep all the songs *somewhere* in memory for accessing chunks of the playlist (since it would be a lot of work to read the playlist from the db, iterate over the database items, all while in-between songs). *I believe this problem can be fixed by doing a 'pre-fetch' at some point right before loading a new playlist chunk, but I plan to experiment with this feature with the IDB Web Worker I just started writing*

--

If there's any further problems that pop up while I'm working on ironing out this issue, feel free to respond here (or in a new issue if it's unrelated to this), thank you for your help with this! 

I'll post a reply as soon as the update is live on the site!

**Comment by noughtmare** [comment]
> As for the performance problems, unfortunately at this very second, they still are going to be present for the next day or two (hopefully it'll be resolved within that time!).

I must say that my performance issue was mostly due to the repeated adding of the same songs to the playlist. I believe that the number of unique songs in my large playlist was under 1000, so better performance is not very urgent for me any more.

**Comment by snuffyDev** [comment]
Currently running a build and then it should be deployed, let me know if any problems still persist! The build is *just* now finishing up, and is currently deploying. Give it a minute or two, check the library page, and you should see two new buttons there. If you do, then you know you're on the latest version!

**Comment by noughtmare** [comment]
Yep, it seems to be working. Thanks!

For my part, this issue can be closed now, but maybe you still want to keep this open to track the performance of very large playlists (again this is not a pressing issue for me now).

**Comment by snuffyDev** [comment]
Glad to hear it! I'll close this now, since your problems have been resolved! 

The performance fixes are being worked on right now, so I'll consider this one done!
Thanks for your help and patience!
